export enum ThemeColor {
  LIGHT = 'light',
  DARK = 'dark',
}

export enum StatusColor {
  Success = 'success',
  Info = 'info',
  Warning = 'warning',
  Danger = 'danger',
}

export enum FunctionName {
  AddPauser = 'AddPauser',
  AddVerified = 'AddVerified',
  Allowance = 'Allowance',
  Approve = 'Approve',
  ApproveAndCall = 'ApproveAndCall',
  AuthorizeOperator = 'AuthorizeOperator',
  BalanceOf = 'BalanceOf',
  BalanceOfID = 'BalanceOfID',
  BalanceOfBatch = 'BalanceOfBatch',
  Burn = 'Burn',
  BurnData = 'BurnData',
  BurnFrom = 'BurnFrom',
  CancelAndReissue = 'CancelAndReissue',
  ImplementInterfaceForAddress = 'ImplementInterfaceForAddress',
  Cap = 'Cap',
  ChangeOwner = 'ChangeOwner',
  CIDByHash = 'CIDByHash',
  Decimals = 'Decimals',
  DecreaseAllowance = 'DecreaseAllowance',
  DecreaseAllowanceAndCall = 'DecreaseAllowanceAndCall',
  DecreaseSupply = 'DecreaseSupply',
  DefaultOperators = 'DefaultOperators',
  Deployed = 'Deployed',
  GetApproved = 'GetApproved',
  GetCurrentFor = 'GetCurrentFor',
  Granularity = 'Granularity',
  HasHash = 'HasHash',
  HolderAt = 'HolderAt',
  HolderCount = 'HolderCount',
  IncreaseAllowance = 'IncreaseAllowance',
  IncreaseAllowanceAndCall = 'IncreaseAllowanceAndCall',
  IncreaseSupply = 'IncreaseSupply',
  IsApprovedForAll = 'IsApprovedForAll',
  IsHolder = 'IsHolder',
  IsPauser = 'IsPauser',
  IsOperatorFor = 'IsOperatorFor',
  IsOwner = 'IsOwner',
  IsSuperseded = 'IsSuperseded',
  IsVerified = 'IsVerified',
  Mint = 'Mint',
  MintWithTokenURI = 'MintWithTokenURI',
  Name = 'Name',
  NewWallet = 'NewWallet',
  OnErc721Received = 'OnErc721Received',
  OnErc1155BatchReceived = 'OnErc1155BatchReceived',
  OnErc1155Received = 'OnErc1155Received',
  OperatorBurn = 'OperatorBurn',
  OperatorSend = 'OperatorSend',
  Owner = 'Owner',
  OwnerOf = 'OwnerOf',
  Rate = 'Rate',
  RemoveVerified = 'RemoveVerified',
  RenounceOwnership = 'RenounceOwnership',
  RenouncePauser = 'RenouncePauser',
  RevokeOperator = 'RevokeOperator',
  SafeBatchTransferFrom = 'SafeBatchTransferFrom',
  SafeTransferFrom = 'SafeTransferFrom',
  SafeTransferFromData = 'SafeTransferFromData',
  SafeTransferFromValueData = 'SafeTransferFromValueData',
  Send = 'Send',
  SetApprovalForAll = 'SetApprovalForAll',
  SetRate = 'SetRate',
  SupportsInterface = 'SupportsInterface',
  Symbol = 'Symbol',
  Target = 'Target',
  TokensReceived = 'TokensReceived',
  TokensToSend = 'TokensToSend',
  TokenByIndex = 'TokenByIndex',
  TokenFallback = 'TokenFallback',
  TokenOfOwnerByIndex = 'TokenOfOwnerByIndex',
  TokenUri = 'TokenUri',
  TotalSupply = 'TotalSupply',
  Transfer = 'Transfer',
  TransferData = 'TransferData',
  TransferDataFallback = 'TransferDataFallback',
  TransferAndCall = 'TransferAndCall',
  TransferFrom = 'TransferFrom',
  TransferFromAndCall = 'TransferFromAndCall',
  TransferOwnership = 'TransferOwnership',
  UpdateVerified = 'UpdateVerified',
  URI = 'URI',
  Pause = 'Pause',
  Pin = 'Pin',
  Paused = 'Paused',
  Unpause = 'Unpause',
  Upgrade = 'Upgrade',
  Resume = 'Resume',
  Wallet = 'Wallet',
  Withdraw = 'Withdraw',
}

export enum ErcName {
  AllFunctions = 'AllFunctions',
  Go20 = 'Erc20',
  Go20Burnable = 'Erc20Burnable',
  Go20Capped = 'Erc20Capped',
  Go20Detailed = 'Erc20Detailed',
  Go20Mintable = 'Erc20Mintable',
  Go20Pausable = 'Erc20Pausable',
  Go165 = 'Erc165',
  Go721 = 'Erc721',
  Go721Burnable = 'Erc721Burnable',
  Go721Receiver = 'Erc721Receiver',
  Go721Metadata = 'Erc721Metadata',
  Go721Enumerable = 'Erc721Enumerable',
  Go721Pausable = 'Erc721Pausable',
  Go721Mintable = 'Erc721Mintable',
  Go721MetadataMintable = 'Erc721MetadataMintable',
  Go721Full = 'Erc721Full',
  Go820 = 'Erc820',
  Go1155 = 'Erc1155',
  Go1155Receiver = 'Erc1155Receiver',
  Go1155Metadata = 'Erc1155Metadata',
  Go223 = 'Erc223',
  Go223Receiver = 'Erc223Receiver',
  Go621 = 'Erc621',
  Go777 = 'Erc777',
  Go777Receiver = 'Erc777Receiver',
  Go777Sender = 'Erc777Sender',
  Go827 = 'Erc827',
  Go884 = 'Erc884',
  Upgradeable = 'Upgradeable',
  Ownable = 'Ownable',
  PauserRole = 'PauserRole',
  GoFS = 'GoFS',
}

export enum EventID {
  Transfer = '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
  OwnerShipTransferred = '0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0',
  PauserAdded = '0x6719d08c1888103bea251a4ed56406bd0c3e69723c8a1686e017e7bbe159b6f8',
  PauserRemoved = '0xcd265ebaf09df2871cc7bd4133404a235ba12eff2041bb89d9c714a2621c7c7e',
  Pinned = '0x7c80eb99758dfe3e8aef5df583c1c9bab5369cf46b930b802f130edcfeac90ca',
  CreatedWallet = '0x89c3649b91d0d77a0655fa3d84b050b21c775ba31bfbc37e440ec3ee04f28927',
}
